version: '3.8'

services:
  db:
    image: postgres:16-alpine  
    container_name: blog_db    
    restart: always           
    ports:
      - "5432:5432"           
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sainath@2005
      POSTGRES_DB: financedb    